### ISSUE TITLE
macOS上的PPPoE拨号方法

### ISSUE THREAD

**Issue by xioi** [Mikachu2333/sdsmu_welcome_tex#2]
可参照官方手册撰写教程，需注意macOS 12.0~14.0有不同的方式设置拨号连接：
https://support.apple.com/zh-cn/guide/mac-help/mchlp27142/14.0/mac/14.0

我亦具备实验条件、可待开学后在此issue下追加实际操作流程。

**Comment by Mikachu2333** [comment]
@xioi 请问情况如何
